### ISSUE TITLE
my fork don't work :)

### ISSUE THREAD

**Issue by smithx** [kaushalmodi/.emacs.d#13]
Why do you load 'cl-lib' only if emacs < 25 ?
init.el:

```
(>=e "25.0"
    nil
  (require 'cl)
  (require 'cl-lib))
```

**Comment by kaushalmodi** [comment]
Hi,

I removed those requires for emacs 25+ because I am using the latest build
of emacs from git and it works fine without requiring cl and cl-lib. I used
to require them unconditionally earlier. But as I don't use emacs 24.5, I
haven't tested thoroughly without those requires on those older versions.
So I decided to keep things as they were on the older versions.

Now I let the packages requiring cl/cl-lib require them. That way the
cl/cl-lib are loaded only when that package is autoloaded.

What version of emacs are you on? What error do you see that traced the
problem to those lines?

I have tested the current state of my config to work fine with emacs 24.5
and emacs 25.0.92 as of today morning.

UPDATE

Also cl-lib would be auto-loaded when you use functions like cl-case, etc. So there is no need to require cl-lib explicitly.

**Comment by kaushalmodi** [comment]
I have updated my config and removed those unnecessary requires ( https://github.com/kaushalmodi/.emacs.d/commit/976e1e46684b5517c8ced8601857a467f911a9be ). I have tested the config to work fine without those cl/cl-lib requires for both emacs 24.5 and emacs 25.0.92.

My guess is that you are using emacs older than 24.5 (probably older than 24.3) and that's why it threw error as it was unable to find the `cl-lib` library. The `cl-lib` library is built into emacs from version 24.3 onwards. To get it, the best way is to upgrade to version 24.5 (or [install cl-lib from elpa](https://elpa.gnu.org/packages/cl-lib.html) using the package manager).

**Comment by smithx** [comment]
Hi, I use Emacs 25.0.92.1 (MS Windows x64 version). I have some packages switched off, another have added.  Do you disable`ido`package ? I use it. Without `cl, cl-lib` requires: after Emacs start,`ido-find-file` function (binded to "`C-x C-f`") doesn't working: "Symbol’s function definition is void: fourth". Some time later, after yasnippet loaded (defer: 20) `ido-find-file` is working.

**Comment by kaushalmodi** [comment]
> Do you disable ido package?

`ido` is disabled by default. I simply do not enable it using `(ido-mode 1)`. I use `ivy`/`counsel` instead. If you use this config _as it is_, `C-x C-f` is bound to `counsel-find-file`.

I also tried the below in my config:

``` el
(ivy-mode -1)
(ido-mode 1)
```

and after that, `ido-find-file` works fine, without the error related to `fourth`.

Also, `M-x ido-mode` followed by `M-x ido-find-file` works fine in `emacs -Q`.

On further investigation, none of the packages installed from Melpa/GNU Elpa using my config use `fourth`. Also `fourth` is defined in the `cl` library. 

So it is one of the packages that you have installed and I don't that's using `fourth`. My guess would be one of the 3rd-party packages associated to `ido`.

**What you need to do?**
- Grep for `\(fourth` in your elpa directory (where all 3rd party packages are installed) and figure out which package uses `fourth`. Contact the package developer to add `(require 'cl)` to their package; or even better use equivalent function from the newer `cl-lib` library (which gets autoloaded). The `cl` library does not get autoloaded as it is deprecated as of emacs 24.3.
- In the meanwhile, doing just `(require 'cl)` in your config should fix this problem.

**Comment by smithx** [comment]
Thank you! You are right, I've  found `fourth` call here:[setup-ido.el](https://github.com/kaushalmodi/.emacs.d/blob/master/setup-files/setup-ido.el#L81) and I've found

```
(require 'cl)
(require 'cl-lib)
```

at begining of `yasnippet.el` package

**Comment by kaushalmodi** [comment]
Thanks for pointing out the issue!

I have updated `setup-ido` and removed `cl` dependency ( https://github.com/kaushalmodi/.emacs.d/commit/4eb4f86a59faefe78d0ae59edce3185be9e57d1f  ). Please update and see if things now work out fine for you.

As I have switched to ivy from ido for quite few months, setup-ido is not being frequently maintained.

**Comment by smithx** [comment]
Thank you! All things work out fine now.
