### ISSUE TITLE
select-enable-primary broke yanking on Windows

### ISSUE THREAD

**Issue by smithx** [kaushalmodi/.emacs.d#16]
Yank don't work with active region when `select-enable-primary` is enabled on Windows.
Possible fix is: [setup-misc.el](https://github.com/kaushalmodi/.emacs.d/blob/master/setup-files/setup-misc.el#L19)

```
;; after mouse selection in X11, you can paste by 'yank' in emacs"
(if (not (eq system-type 'windows-nt))
    (>=e "25.0"
        (setq select-enable-primary t)  ; if emacs 25.0 or newer
      (setq x-select-enable-primary t))) ; if older
```

**Comment by kaushalmodi** [comment]
Can you elaborate on what is broken with yanks, with steps to recreate the problem? 

What was the expected outcome of those steps and what do you see instead?

**Comment by smithx** [comment]
If I perform yanking (C-y) while buffer has active region, first time it is yanking but not replace selected text. When I try to yank next times yanking are not performed, region become not active, selected text come to kill ring (clipboard) instead of to be replaced by previous content of clipboard

From documentation about `select-enable-primary`

```
Documentation:
Non-nil means cutting and pasting uses the primary selection
The existence of a primary selection depends on the underlying GUI you use.
**E.g. it doesn’t exist under MS-Windows**.
```

**Comment by kaushalmodi** [comment]
Even though primary selection does not exist on Windows, the pasting mechanism mimics what one would need to do in Linux.

If a text is selected in Linux, the simple act of selection would save it to the kill-ring. So then when you do `C-y`, the pasted text would be the same as the selected text. So to paste what you killed before you selected the text, you would next need to do `M-y` (bound to `yank-pop` by default). For more info, do `C-h r m Earlier Kills`.

Here is the sequence of actions needed when pasting over a selected region which works consistently in Windows/Linux (note that below works as we have `delete-selection-mode` enabled in this config):
- Copy the text you wish to paste over the selection
- Select a region
- `C-y M-y`

With your suggestion, the last step would become just `C-y`.
As this boils down to personal preferences, I have rearranged the code ( https://github.com/kaushalmodi/.emacs.d/commit/af01a73c0ab709daf7ff160c5d8f17e9f0643fea ) so that you can override this in your `~/.emacs.d/personal/setup-personal.el`.

After updating the config from github, put your suggested snippet in your `~/.emacs.d/personal/setup-personal.el` and things should work as you expected in Windows.

_PS: A note about your suggestion: For me the `system-type` is `'w32` on Windows 7._

**Comment by smithx** [comment]
Thank you, You are right, all things works as you describe.
