### ISSUE TITLE
remove assignment of eww-search-prefix in modi/eww--go-to-first-search-result

### ISSUE THREAD

**Issue by beacoder** [kaushalmodi/.emacs.d#27]
Hello, I got a question:
since you have setq for variable eww-search-prefix before, why do you assign a new value in the function
modi/eww--go-to-first-search-result again ?

**Comment by kaushalmodi** [comment]
Hello,

Glad to see someone taking interest in that little function :)

A while back I had tried to generalize `modi/eww--go-to-first-search-result` for different search engines but it didn't work as expected. So then I forced that function to always use google.com (as anyways I use that by default). 

Give me a day. I'll make it customizable so that you can add an `("my.search.engine" . "first search regexp")` element to that customizable variable.
